[package]
name = "LeafOS"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.37.0", features = ["panic_handler"] }
acpi = { version = "6.1.1", default-features = false }

[target.x86_64-unknown-uefi.dependencies]
x86_64 = "0.15.4"

# 仅在 ARM 架构使用的依赖
[target.'cfg(target_arch = "arm")'.dependencies]
arm = "0.0.1"

# 仅在 aarch64 架构使用的依赖
[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = "0.0.14"

[target.'cfg(target_arch = "riscv64gc")'.dependencies]
riscv = "0.16.0"

[target.'cfg(target_arch = "loongarch64")'.dependencies]
loongArch64 = "0.2.6"
